options -! -!k -!s

diff --git a/vamos b/vamos
--- a/vamos
+++ b/vamos
@@ -48,9 +48,10 @@ if [ "$*" == "---usage" ]; then
     echo "    $VAMOS -i                   # install $VAMOS stuff"
     echo "    $VAMOS -p                   # print virtual environment dir path"
     echo "    $VAMOS -r                   # remove virtual Python environment"
-    echo "    $VAMOS -s                   # startup playground"
+    echo "    $VAMOS -s                   # setup playground"
     echo "    $VAMOS -u                   # uninstall $VAMOS"
     echo "    $VAMOS -w                   # change working directory"
+    echo "    $VAMOS -!                   # install as /usr/local/bin/$VAMOS"
 
     exit 0
 fi
@@ -355,6 +356,39 @@ if [ "$1" == "-w" ]; then
     unset _vENV;  unset _ERR
     unset _VAMOS_VERSION  # cleanup, since we might run in sourced mode
     unset _VAMOS     # cleanup, since we might run in sourced mode
+    return 0 2>/dev/null || exit 0  # safe return/exit
+fi
+
+#===============================================================================
+# install in /usr/local/bin
+#===============================================================================
+
+if [ "$*" == "-!" ] || [ "$*" == "!k" ] || [ "$*" == "!s" ]; then
+    (return 0 2>/dev/null) && _SOURCED=1 || _SOURCED=0  # determine _SOURCED
+
+    if [ "$_SOURCED" == 0 ]; then
+        bash $_APP ---unsourced $*
+    elif [ "$*" == "-!k" ]; then
+        bash $_APP ---!k
+    elif [ "$*" == "-!s" ]; then
+        bash $_APP ---!s
+    else
+        bash $_APP ---!
+    fi
+
+        # check system requirements
+
+    bash $_APP --check
+        
+        # define aliases `vamos` and `wd`
+
+    alias vamos="source /usr/local/bin/vamos"
+    alias wd="source /usr/local/bin/vamos -w"
+
+    unset _SOURCED
+    unset _VAMOS_VERSION  # cleanup, since we might run in sourced mode
+    unset _VAMOS     # cleanup, since we might run in sourced mode
+    unset _APP
     return 0 2>/dev/null || exit 0  # safe return/exit
 fi
 
@@ -677,6 +711,82 @@ if [ "$*" == '-?' ]; then
 fi
 
 #===============================================================================
+# install ./vamos as /usr/local/bin/vamos
+#===============================================================================
+
+if [ "$*" == "---!" ] || [ "$*" == "---!k" ] \
+                      || [ "$*" == "---!s" ] || [ "$*" == "---!ks" ]; then
+    BIN=/usr/local/bin
+    TARGET=$BIN/vamos
+    TEMPCOPY=~vamos
+
+    if [ "$*" != "---!s"] && [ "$*" != "---!ks"]; then
+        $ECHO -@C "installing vamos in $BIN ..."
+    fi
+
+    GITRAW=https://raw.githubusercontent.com
+    URL=$GITRAW/$_REPO/main/vamos
+
+    if [ "$*" != "---!s"] && [ "$*" != "---!ks"]; then
+        $ECHO -@C "downloading $VAMOS ..."
+    fi
+
+       # actual installation
+
+    if [ "$*" != "---!s"] && [ "$*" != "---!ks"]; then
+        $ECHO -@Y "curl $URL >$TEMPCOPY"
+    fi
+
+    if [ "$*" != "---!s" ] && [ "$*" != "---!ks" ]; then
+        curl $URL >$TARGET || ERR=1
+    else
+        curl -s $URL >$TARGET || ERR=1
+    fi
+
+        # make executable
+
+    if [ "$ERR" == 0 ]; then
+        chmod +x $TARGET || ERR=1
+    fi
+
+        # install in /usr/local/bin
+
+    if [ "$ERR" == 0 ]; then
+        bash $TEMPCOPY ---install $TEMPCOPY  # copy ./~vamos to /usr/local/bin
+    fi
+
+        # verification
+
+    if [ "$ERR" == 0 ]; then
+        _VERIFY=`bash $TARGET --version`
+        _MORE='(check with `vamos -?`)'
+
+        if [ "$_VERIFY" == "$_VERSION" ]; then
+            printf $_GREEN
+            echo "vamos (version $_VERSION) successfully installed "$_MORE
+            printf $_NORMAL
+
+        else
+            printf $_RED
+            echo 'error: final check for vamos installation failed'
+            echo 'expected `vamos --version` to return '"$_VERSION"
+            printf $_NORMAL
+            ERR=1
+        fi
+
+        unset _VERIFY
+        unset _MORE
+    fi
+
+        # remove temporary files
+
+    if [ "$*" != "---!k" ] && [ "$*" != "---!ks" ]; then
+        $ECHO -@C removing './vamos ...'
+        #rm $TARGET
+    fi
+fi
+
+#===============================================================================
 # comprehensive help
 #===============================================================================
 
@@ -934,6 +1044,30 @@ fi
 
 if [ "$*" == "--version" ]; then
     echo $VERSION
+    exit 0
+fi
+
+#===============================================================================
+# install helper: copy ./vamos to /usr/local/bin/vamos and chmod +x
+#===============================================================================
+
+if [ "$*" == "---install" ]; then
+    _OK=1
+    shift;  TEMPCOPY=$1
+    if [ -f $TEMPCOPY ]; then
+        printf $_YELLOW
+        echo 'installing `vamos` in /usr/local/bin ...'
+        printf $_NORMAL
+        sudo cp $TEMPCOPY /usr/local/bin/vamos || _OK=0
+
+        if [ "$_OK" == 0 ]; then
+            echo "$TEMPCOPY ---install: cannot copy $TEMPCOPY to /usr/local/bin/vamos"
+            exit 1
+        fi
+    else
+        echo "$TEMPCOPY ---install: no file $TEMPCOPY"
+        exit 1
+    fi
     exit 0
 fi
 
